"""empty message

Revision ID: 471a47476228
Revises: 147d22cf3d4e
Create Date: 2022-11-02 16:59:25.105374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '471a47476228'
down_revision = '147d22cf3d4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habit', sa.Column('editable', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('habit', 'editable')
    # ### end Alembic commands ###
