"""empty message

Revision ID: 488e181767e2
Revises: 8d5fd17b51b0
Create Date: 2022-10-21 17:09:16.696152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '488e181767e2'
down_revision = '8d5fd17b51b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habit', sa.Column('num_times_repeated', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('habit', 'num_times_repeated')
    # ### end Alembic commands ###
