"""empty message

Revision ID: 90eb78786c77
Revises: 4d1bdd3c8336
Create Date: 2022-10-12 16:49:56.912885

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '90eb78786c77'
down_revision = '4d1bdd3c8336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todo', 'finished_at',
               existing_type=postgresql.TIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todo', 'finished_at',
               existing_type=postgresql.TIME(),
               nullable=False)
    # ### end Alembic commands ###
