"""empty message

Revision ID: 927e33a36c20
Revises: a23b25647b62
Create Date: 2022-10-17 18:10:01.783660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '927e33a36c20'
down_revision = 'a23b25647b62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todo', 'state',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todo', 'state',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
