"""empty message

Revision ID: f5d89951c7d0
Revises: f2fb988866e1
Create Date: 2022-10-13 23:16:59.587822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5d89951c7d0'
down_revision = 'f2fb988866e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('habit', 'frequency')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habit', sa.Column('frequency', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
